info:
  prefix: 'puppet-module'
  authors: 'Puppet, Inc.'
  email: 'puppet-module-gems-maintainers@puppet.com'
  homepage: 'https://github.com/puppetlabs/puppet-module-gems'
  licenses: 'Apache-2.0'
  summary: 'A gem used to manage Puppet module dependencies.'
  version: '0.3.8'
