Gem::Specification.new do |s|
  s.name        = 'puppet-module-posix-dev-r2.3'
  s.version     = '0.3.4'
  s.summary     = 'A gem used to manage Puppet module dependencies.'
  s.authors     = 'Puppet, Inc.'
  s.email       = 'puppet-module-gems-maintainers@puppet.com'
  s.homepage    = 'https://github.com/puppetlabs/puppet-module-gems'
  s.license     = 'Apache-2.0'

  # Gem Dependencies
  s.add_runtime_dependency 'simplecov', '>= 0.14.1', '< 1.0.0'
  s.add_runtime_dependency 'puppet-blacksmith', '>= 3.4.0'
  s.add_runtime_dependency 'codecov', '~> 0.1.10'
  s.add_runtime_dependency 'gettext-setup', '~> 0.26'
  s.add_runtime_dependency 'metadata-json-lint', '>= 2.0.2', '< 3.0.0'
  s.add_runtime_dependency 'mocha', '>= 1.0.0', '< 1.2.0'
  s.add_runtime_dependency 'parallel_tests', '>= 2.14.1', '< 2.14.3'
  s.add_runtime_dependency 'pry', '~> 0.10.4'
  s.add_runtime_dependency 'puppet-lint', '>= 2.3.0', '< 3.0.0'
  s.add_runtime_dependency 'puppet_pot_generator', '~> 1.0'
  s.add_runtime_dependency 'puppet-strings', '~> 2.0'
  s.add_runtime_dependency 'puppet-syntax', '>= 2.4.1', '< 3.0.0'
  s.add_runtime_dependency 'puppetlabs_spec_helper', '>= 2.8.0', '< 3.0.0'
  s.add_runtime_dependency 'rainbow', '~> 2.0'
  s.add_runtime_dependency 'rspec-puppet', '>= 2.3.2', '< 3.0.0'
  s.add_runtime_dependency 'rspec-puppet-facts', '~> 1.8'
  s.add_runtime_dependency 'rubocop', '~> 0.49.0'
  s.add_runtime_dependency 'rubocop-i18n', '~> 1.2.0'
  s.add_runtime_dependency 'rubocop-rspec', '~> 1.16.0'
  s.add_runtime_dependency 'rspec_junit_formatter', '~> 0.2'
  s.add_runtime_dependency 'simplecov-console', '~> 0.4.2'
  s.add_runtime_dependency 'specinfra', '2.67.3'
end
